### ISSUE TITLE
Support for querying labels and annotations

### ISSUE THREAD

**Issue by mavenraven** [cloudquery/cq-provider-k8s#1]
It would be tremendously useful to include labels and annotations as something that could be queried. I might have time to make a PR for this at some point. Would you prefer a single polymorphic labels table that is shared across resources, or something like PodLabels?

**Comment by roneli** [comment]
Hi @mavenraven we added many [resources ](https://github.com/cloudquery/cq-provider-k8s/blob/main/CHANGELOG.md) in [v0.3.0](https://github.com/cloudquery/cq-provider-k8s/releases/tag/v0.3.0), they all support annotations and labels
